name: Docker Build and Push

on:
  push:
    tags:
      - "*"

env:
  IMAGE_NAME: tianli-cdn
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Sleep 5 minutes
        run: sleep 300

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Update Dockerfile with tag
        run: sed -i "s/\$BUILD_VERSION/${{ github.event.ref }}/g" /docker/dockerfile
      
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.event.ref }} .
      
      - name: Push Docker image
        if: success()
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.event.ref }}